name: MemeAntiMacro
version: ${project.version}
main: pl.memexurer.antymakiero.AntiClickerPlugin
api-version: '1.8'
depend:
  - ProtocolLib
authors: [Memexurer]
description: Plugin na blokowanie makra
